# Generated by Django 3.0.7 on 2020-06-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='user_comment',
        ),
    ]
